- hosts: all
  strategy: free
  remote_user: root
  vars:
    local_ip: "{{ansible_default_ipv4['address']}}"
    node_num: "{{ local_ip | regex_replace('([0-9]{1,3}\\.){3}') }}"
    hostname: "{{ansible_hostname}}"
  tasks:
    - name: install useful app
      yum:
        name:
        - git
        - java-1.8.0-openjdk-devel
        - htop
    - name: install kibana
      yum: 
       name: 
       - /opt/{{ esVersion }}/kibana-{{ esVersion }}-x86_64.rpm
    - name: set yml config
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
      with_items: 
        - {regexp: '^server.port:', line: 'server.port: 5601' }
        - {regexp: '^server.host:', line: 'server.host: "{{local_ip}}"' }
        - {regexp: '^elasticsearch.hosts: ', line: 'elasticsearch.hosts: ["http://{{ local_ip }}:9200"]' }
        - {regexp: '[#]?i18n.locale: ', line: 'i18n.locale: "zh-CN"' }
    - name: start kibana
      service: 
        name: kibana
        enabled: yes
        state: started